### ISSUE TITLE
Page footer styling issues

### ISSUE THREAD

**Issue by drzax** [abcnews/timeline-navigation#1]
Styling issues in the footer of timeline articles has been reported by @adritek:

> We noticed some of the CSS was acting up on the timeline interactives for P1 news stories (in the footer). https://www.abc.net.au/news/2019-02-21/cyclone-oma-is-not-the-first-cyclone-to-threaten-brisbane/10829026

**Comment by nathanhoad** [comment]
This should be fixed now.
